#!/bin/sh
# Test suite
# by Patrick Melanson

usage () {
    echo "usage: $0 suite-file program" 1>&2
}

if [ $# -ne 2 ]; then
    usage
    exit 1
fi

tmpfilestodelete=""

cleanup() {
    rm -f "$tmpfilestodelete"
    return $?
}

trap cleanup SIGINT

if [ ! -x $2 ]; then
    echo "Cannot execute or find $2"
    exit 3
fi

for test in $(cat $1); do
    prefix=$(dirname "$1")
    if [ ! -f "${prefix}/${test}.in" ] || [ ! -r "${prefix}/${test}.in" ]; then
        echo "Cannnot find ${prefix}/${test}.in, or it is not a file" 1>&2
        exit 2
    fi
    if [ ! -f "${prefix}/${test}.out" ] || [ ! -r "${prefix}/${test}.out" ]; then
        echo "Cannot find ${prefix}/${test}.out, or it is not a file" 1>&2
        exit 2
    fi

    tmpfile="$(mktemp --suffix=$test)"
    tmpfilestodelete="$tmpfilestodelete $tmpfile"

    if [ -f "${prefix}/${test}.args" ]; then
        $2 $(cat "${prefix}/${test}.args") < "${prefix}/${test}.in" > $tmpfile
    else
        $2 < "${prefix}/${test}.in" > $tmpfile
    fi

    echo "Running ${test}"

    if [ "$(cmp $tmpfile ${prefix}/${test}.out)" != "" ]; then
        echo "Test failed: $test"
        echo "-------"
        echo "Input:"
        cat "${test}.in"
        echo "-------"
        echo "Expected:"
        cat "${test}.out"
        echo "-------"
        echo "Actual:"
        cat $tmpfile
        echo "-------"
        echo "Diff:"
        diff "${test}.out" $tmpfile
        echo "===================================="
    fi
    rm -f $tmpfile
    rmretval=$?
    if [ $rmretval -ne 0 ]; then
        echo "rm $tmpfile returned $rmretval"
    fi
    tmpfilestodelete=${tmpfilestodelete/$tmpfile/}  # don't try deleting again
done
