#!/bin/sh
# Test suite
# by Patrick Melanson

usage () {
  echo "usage: $0 suite-file program" 1>&2
}

if [ $# -ne 2 ]; then
  usage
  exit 1
fi

for test in $(cat $1); do
  if [ ! -f "${test}.in" ] || [ ! -r "${test}.in" ]; then
    echo "Cannnot find ${test}.in, or it is not a file" 1>&2
    exit 2
  fi
  if [ ! -f "${test}.out" ] || [ ! -r "${test}.out" ]; then
    echo "Cannot find ${test}.out, or it is not a file" 1>&2
    exit 2
  fi

  tmpfile=$(mktemp)

  if [ -f "${test}.args" ]; then
    $2 $(cat "${test}.args") < "${test}.in" > $tmpfile
  else
    $2 < "${test}.in" > $tmpfile
  fi

  if [ "$(cmp $tmpfile ${test}.out)" != "" ]; then
    echo "Test failed: $test"
    echo "-------"
    echo "Input:"
    cat "${test}.in"
    echo "-------"
    echo "Expected:"
    cat "${test}.out"
    echo "-------"
    echo "Actual:"
    cat $tmpfile
    echo "-------"
    echo "Diff:"
    diff "${test}.out" $tmpfile
    echo "===================================="
  fi
  rm $tmpfile
done
